### ISSUE TITLE
rejoin problem.

### ISSUE THREAD

**Issue by successed** [biscuut/VoidChest#1]
I can not break the chest after entering the game, but I get money from the goods sold in the crate.

So, i tested. i rejoin the my server and this payment is not sending message me and the plugin tells me that it can't break the chest.Can you fix this ?

**Comment by successed** [comment]
and please add hook griefprevention and worldguard support.

**Comment by biscuut** [comment]
My plugin doesn't directly hook into other plugins to check if you can break the chest (so sorry, I don't add hooks). If you can't break the chest there are 2 possiblities:
a. You aren't the owner of the chest & anyone-can-break: false (doubt it)
b. Another plugin is not allowing you to break the chest- make sure you get permission from that plugin. Alternatively you can use /sc bypass to bypass other plugin's permission checks.

Also in the future, you only have to ask for support in one place. Please do not create all 3- a discussion post, a private message, and a github issue. Just one is fine, thanks! :)

**Comment by successed** [comment]
once the player leaves the game and re-enters the my server, he can place a new crate over the chest limit.
my settings : http://prntscr.com/n2bwq7
This is a default player : http://prntscr.com/n2bxns
and he place 2 sellchest chest!
