### ISSUE TITLE
load of laggy. 1.14.x paper #80

### ISSUE THREAD

**Issue by successed** [biscuut/VoidChest#2]
http://prntscr.com/o0dkkm

can you fix this ?

**Comment by biscuut** [comment]
responded on spigot -> reposting here "unfortunately the process of going through all the chests and grabbing all the item prices requires a bit of processing power, i will check it over when i get time but no promises... for now i would recommend putting the sell-interval to something higher than 1 second, like 3 or 4 seconds, it will help. "

**Comment by successed** [comment]
> responded on spigot -> reposting here "unfortunately the process of going through all the chests and grabbing all the item prices requires a bit of processing power, i will check it over when i get time but no promises... for now i would recommend putting the sell-interval to something higher than 1 second, like 3 or 4 seconds, it will help. "

i have 10 seconds now. t,y for answer.
